//! GENERATED by `tools/codegen.py` — do not edit by hand.
//! M3c skeleton bindings for the FreeCAD App document/object surface.
//! Method bodies are `todo!()`; behaviour is filled in by hand-written glue.

#![allow(non_snake_case, unused_variables, unused_imports, clippy::all)]

use pyo3::prelude::*;
use pyo3::types::{PyAnyMethods, PyDict, PyTuple, PyType};

#[pyclass(name = "Document", module = "ferrocad_gen")]
struct Document;

#[pymethods]
impl Document {
    #[getter]
    fn DependencyGraph(&self) -> String { String::new() }
    #[getter]
    fn ActiveObject(&self, py: Python<'_>) -> PyObject { py.None() }
    #[getter]
    fn Objects(&self) -> Vec<PyObject> { Vec::new() }
    #[getter]
    fn TopologicalSortedObjects(&self) -> Vec<PyObject> { Vec::new() }
    #[getter]
    fn RootObjects(&self) -> Vec<PyObject> { Vec::new() }
    #[getter]
    fn RootObjectsIgnoreLinks(&self) -> Vec<PyObject> { Vec::new() }
    #[getter]
    fn UndoMode(&self) -> i64 { 0 }
    #[setter]
    fn set_UndoMode(&mut self, value: i64) { let _ = value; }
    #[getter]
    fn UndoRedoMemSize(&self) -> i64 { 0 }
    #[getter]
    fn UndoCount(&self) -> i64 { 0 }
    #[getter]
    fn RedoCount(&self) -> i64 { 0 }
    #[getter]
    fn UndoNames(&self) -> Vec<PyObject> { Vec::new() }
    #[getter]
    fn RedoNames(&self) -> Vec<PyObject> { Vec::new() }
    #[getter]
    fn Name(&self) -> String { String::new() }
    #[getter]
    fn RecomputesFrozen(&self) -> bool { false }
    #[setter]
    fn set_RecomputesFrozen(&mut self, value: bool) { let _ = value; }
    #[getter]
    fn HasPendingTransaction(&self) -> bool { false }
    #[getter]
    fn InList(&self) -> Vec<PyObject> { Vec::new() }
    #[getter]
    fn OutList(&self) -> Vec<PyObject> { Vec::new() }
    #[getter]
    fn Restoring(&self) -> bool { false }
    #[getter]
    fn Partial(&self) -> bool { false }
    #[getter]
    fn Importing(&self) -> bool { false }
    #[getter]
    fn Recomputing(&self) -> bool { false }
    #[getter]
    fn Transacting(&self) -> bool { false }
    #[getter]
    fn OldLabel(&self) -> String { String::new() }
    #[getter]
    fn Temporary(&self) -> bool { false }
    #[pyo3(signature = ())]
    fn save(&self) -> () { todo!("Document.save") }
    #[pyo3(signature = (path))]
    fn saveAs(&self, path: &str) -> () { todo!("Document.saveAs") }
    #[pyo3(signature = (path))]
    fn saveCopy(&self, path: &str) -> () { todo!("Document.saveCopy") }
    #[pyo3(signature = ())]
    fn canWriteRecoverySnapshot(&self) -> bool { todo!("Document.canWriteRecoverySnapshot") }
    #[pyo3(signature = (path))]
    fn load(&self, path: &str) -> () { todo!("Document.load") }
    #[pyo3(signature = ())]
    fn restore(&self) -> () { todo!("Document.restore") }
    #[pyo3(signature = ())]
    fn isSaved(&self) -> bool { todo!("Document.isSaved") }
    #[pyo3(signature = ())]
    fn getProgramVersion(&self) -> String { todo!("Document.getProgramVersion") }
    #[pyo3(signature = ())]
    fn getFileName(&self) -> String { todo!("Document.getFileName") }
    #[pyo3(signature = (namespace))]
    fn settings(&self, namespace: &str) -> PyObject { todo!("Document.settings") }
    #[pyo3(signature = (objName))]
    fn getUniqueObjectName(&self, objName: &str) -> String { todo!("Document.getUniqueObjectName") }
    #[pyo3(signature = (path))]
    fn mergeProject(&self, path: &str) -> () { todo!("Document.mergeProject") }
    #[pyo3(signature = (path = ""))]
    fn exportGraphviz(&self, path: &str) -> PyObject { todo!("Document.exportGraphviz") }
    #[pyo3(signature = (name = ""))]
    fn openTransaction(&self, name: &str) -> () { todo!("Document.openTransaction") }
    #[pyo3(signature = ())]
    fn abortTransaction(&self) -> () { todo!("Document.abortTransaction") }
    #[pyo3(signature = ())]
    fn commitTransaction(&self) -> () { todo!("Document.commitTransaction") }
    fn addObject(&self, type_: &str, name: &str, objProxy: PyObject, viewProxy: PyObject, attach: bool, viewType: &str) -> PyObject { todo!("Document.addObject") }
    fn addProperty(&self, type_: &str, name: &str, group: &str, doc: &str, attr: i64, read_only: bool, hidden: bool, locked: bool, enum_vals: Vec<PyObject>) -> PyObject { todo!("Document.addProperty") }
    #[pyo3(signature = (name))]
    fn removeProperty(&self, name: &str) -> bool { todo!("Document.removeProperty") }
    #[pyo3(signature = (object))]
    fn removeObject(&self, object: PyObject) -> () { todo!("Document.removeObject") }
    #[pyo3(signature = (object, recursive = false, return_all = false))]
    fn copyObject(&self, object: PyObject, recursive: bool, return_all: bool) -> PyObject { todo!("Document.copyObject") }
    #[pyo3(signature = (object, with_dependencies = false))]
    fn moveObject(&self, object: PyObject, with_dependencies: bool) -> PyObject { todo!("Document.moveObject") }
    fn importLinks(&self, source: PyObject) -> Vec<PyObject> { todo!("Document.importLinks") }
    #[pyo3(signature = ())]
    fn undo(&self) -> () { todo!("Document.undo") }
    #[pyo3(signature = ())]
    fn redo(&self) -> () { todo!("Document.redo") }
    #[pyo3(signature = ())]
    fn clearUndos(&self) -> () { todo!("Document.clearUndos") }
    #[pyo3(signature = ())]
    fn clearDocument(&self) -> () { todo!("Document.clearDocument") }
    #[pyo3(signature = (closable))]
    fn setClosable(&self, closable: bool) -> () { todo!("Document.setClosable") }
    #[pyo3(signature = ())]
    fn isClosable(&self) -> bool { todo!("Document.isClosable") }
    #[pyo3(signature = (autoCreated))]
    fn setAutoCreated(&self, autoCreated: bool) -> () { todo!("Document.setAutoCreated") }
    #[pyo3(signature = ())]
    fn isAutoCreated(&self) -> bool { todo!("Document.isAutoCreated") }
    fn recompute(&self, objs: PyObject, force: bool, check_cycle: bool) -> i64 { todo!("Document.recompute") }
    #[pyo3(signature = ())]
    fn mustExecute(&self) -> bool { todo!("Document.mustExecute") }
    #[pyo3(signature = ())]
    fn purgeTouched(&self) -> () { todo!("Document.purgeTouched") }
    #[pyo3(signature = ())]
    fn isTouched(&self) -> bool { todo!("Document.isTouched") }
    #[pyo3(signature = (name))]
    fn getObject(&self, name: PyObject) -> PyObject { todo!("Document.getObject") }
    #[pyo3(signature = (label))]
    fn getObjectsByLabel(&self, label: &str) -> Vec<PyObject> { todo!("Document.getObjectsByLabel") }
    #[pyo3(signature = (Type = "", Name = "", Label = ""))]
    fn findObjects(&self, Type: &str, Name: &str, Label: &str) -> Vec<PyObject> { todo!("Document.findObjects") }
    fn getLinksTo(&self, obj: PyObject, options: i64, maxCount: i64) -> Vec<PyObject> { todo!("Document.getLinksTo") }
    #[pyo3(signature = ())]
    fn supportedTypes(&self) -> Vec<PyObject> { todo!("Document.supportedTypes") }
    #[pyo3(signature = (name))]
    fn getTempFileName(&self, name: &str) -> String { todo!("Document.getTempFileName") }
    #[pyo3(signature = (sort = true))]
    fn getDependentDocuments(&self, sort: bool) -> Vec<PyObject> { todo!("Document.getDependentDocuments") }
    #[pyo3(signature = ())]
    fn getBookedTransactionID(&self) -> i64 { todo!("Document.getBookedTransactionID") }
}

#[pyclass(name = "DocumentObject", module = "ferrocad_gen")]
struct DocumentObject;

#[pymethods]
impl DocumentObject {
    #[getter]
    fn OutListProp(&self) -> Vec<PyObject> { Vec::new() }
    #[getter]
    fn OutList(&self) -> Vec<PyObject> { Vec::new() }
    #[getter]
    fn OutListRecursive(&self) -> Vec<PyObject> { Vec::new() }
    #[getter]
    fn InList(&self) -> Vec<PyObject> { Vec::new() }
    #[getter]
    fn InListProp(&self) -> Vec<PyObject> { Vec::new() }
    #[getter]
    fn InListRecursive(&self) -> Vec<PyObject> { Vec::new() }
    #[getter]
    fn FullName(&self) -> String { String::new() }
    #[getter]
    fn Name(&self) -> String { String::new() }
    #[getter]
    fn Document(&self, py: Python<'_>) -> PyObject { py.None() }
    #[getter]
    fn State(&self) -> Vec<PyObject> { Vec::new() }
    #[getter]
    fn ViewObject(&self, py: Python<'_>) -> PyObject { py.None() }
    #[getter]
    fn MustExecute(&self) -> bool { false }
    #[getter]
    fn ID(&self) -> i64 { 0 }
    #[getter]
    fn Removing(&self) -> bool { false }
    #[getter]
    fn Parents(&self) -> Vec<PyObject> { Vec::new() }
    #[getter]
    fn OldLabel(&self) -> String { String::new() }
    #[getter]
    fn NoTouch(&self) -> bool { false }
    #[setter]
    fn set_NoTouch(&mut self, value: bool) { let _ = value; }
    fn addProperty(&self, type_: &str, name: &str, group: &str, doc: &str, attr: i64, read_only: bool, hidden: bool, locked: bool, enum_vals: Vec<PyObject>) -> PyObject { todo!("DocumentObject.addProperty") }
    #[pyo3(signature = (string))]
    fn removeProperty(&self, string: &str) -> bool { todo!("DocumentObject.removeProperty") }
    #[pyo3(signature = ())]
    fn supportedProperties(&self) -> Vec<PyObject> { todo!("DocumentObject.supportedProperties") }
    #[pyo3(signature = (property_name = ""))]
    fn touch(&self, property_name: &str) -> () { todo!("DocumentObject.touch") }
    #[pyo3(signature = ())]
    fn purgeTouched(&self) -> () { todo!("DocumentObject.purgeTouched") }
    #[pyo3(signature = ())]
    fn enforceRecompute(&self) -> () { todo!("DocumentObject.enforceRecompute") }
    #[pyo3(signature = (name, expression, comment = ""))]
    fn setExpression(&self, name: &str, expression: PyObject, comment: &str) -> () { todo!("DocumentObject.setExpression") }
    #[pyo3(signature = (name))]
    fn clearExpression(&self, name: &str) -> () { todo!("DocumentObject.clearExpression") }
    #[classmethod]
    #[pyo3(signature = (expression))]
    fn evalExpression(_cls: &Bound<'_, PyType>, expression: &str) -> PyObject { todo!("DocumentObject.evalExpression") }
    #[pyo3(signature = (recursive = false))]
    fn recompute(&self, recursive: bool) -> bool { todo!("DocumentObject.recompute") }
    #[pyo3(signature = ())]
    fn getStatusString(&self) -> String { todo!("DocumentObject.getStatusString") }
    #[pyo3(signature = ())]
    fn isValid(&self) -> bool { todo!("DocumentObject.isValid") }
    fn getSubObject(&self, subname: PyObject, retType: i64, matrix: PyObject, transform: bool, depth: i64) -> PyObject { todo!("DocumentObject.getSubObject") }
    #[pyo3(signature = (subname))]
    fn getSubObjectList(&self, subname: &str) -> Vec<PyObject> { todo!("DocumentObject.getSubObjectList") }
    #[pyo3(signature = (reason = 0))]
    fn getSubObjects(&self, reason: i64) -> Vec<PyObject> { todo!("DocumentObject.getSubObjects") }
    fn getLinkedObject(&self, recursive: bool, matrix: PyObject, transform: bool, depth: i64) -> PyObject { todo!("DocumentObject.getLinkedObject") }
    #[pyo3(signature = (element, visible = true))]
    fn setElementVisible(&self, element: &str, visible: bool) -> i64 { todo!("DocumentObject.setElementVisible") }
    #[pyo3(signature = (element))]
    fn isElementVisible(&self, element: &str) -> i64 { todo!("DocumentObject.isElementVisible") }
    #[pyo3(signature = ())]
    fn hasChildElement(&self) -> bool { todo!("DocumentObject.hasChildElement") }
    #[pyo3(signature = ())]
    fn getParentGroup(&self) -> PyObject { todo!("DocumentObject.getParentGroup") }
    #[pyo3(signature = ())]
    fn getParentGeoFeatureGroup(&self) -> PyObject { todo!("DocumentObject.getParentGeoFeatureGroup") }
    #[pyo3(signature = ())]
    fn getParent(&self) -> PyObject { todo!("DocumentObject.getParent") }
    #[pyo3(signature = (target))]
    fn getPathsByOutList(&self, target: PyObject) -> Vec<PyObject> { todo!("DocumentObject.getPathsByOutList") }
    #[pyo3(signature = (subname))]
    fn resolve(&self, subname: &str) -> Vec<PyObject> { todo!("DocumentObject.resolve") }
    #[pyo3(signature = (subname, append = false, type_ = 0))]
    fn resolveSubElement(&self, subname: &str, append: bool, type_: i64) -> Vec<PyObject> { todo!("DocumentObject.resolveSubElement") }
    #[pyo3(signature = (parent, recursive = true))]
    fn adjustRelativeLinks(&self, parent: PyObject, recursive: bool) -> bool { todo!("DocumentObject.adjustRelativeLinks") }
    #[pyo3(signature = (property_name, restored = false))]
    fn getElementMapVersion(&self, property_name: &str, restored: bool) -> String { todo!("DocumentObject.getElementMapVersion") }
    #[pyo3(signature = ())]
    fn isAttachedToDocument(&self) -> bool { todo!("DocumentObject.isAttachedToDocument") }
    fn getPlacementOf(&self, subname: &str, target: PyObject) -> PyObject { todo!("DocumentObject.getPlacementOf") }
    #[pyo3(signature = (name, targetObj))]
    fn moveProperty(&self, name: &str, targetObj: PyObject) -> () { todo!("DocumentObject.moveProperty") }
}

#[pyclass(name = "PropertyContainer", module = "ferrocad_gen")]
struct PropertyContainer;

#[pymethods]
impl PropertyContainer {
    #[getter]
    fn PropertiesList(&self) -> Vec<PyObject> { Vec::new() }
    #[pyo3(signature = (name, checkOwner = 0))]
    fn getPropertyByName(&self, name: &str, checkOwner: i64) -> PyObject { todo!("PropertyContainer.getPropertyByName") }
    #[pyo3(signature = (name))]
    fn getPropertyTouchList(&self, name: &str) -> Vec<PyObject> { todo!("PropertyContainer.getPropertyTouchList") }
    #[pyo3(signature = (name))]
    fn getTypeOfProperty(&self, name: &str) -> Vec<PyObject> { todo!("PropertyContainer.getTypeOfProperty") }
    #[pyo3(signature = (name))]
    fn getTypeIdOfProperty(&self, name: &str) -> String { todo!("PropertyContainer.getTypeIdOfProperty") }
    #[pyo3(signature = (name, type_))]
    fn setEditorMode(&self, name: &str, type_: PyObject) -> () { todo!("PropertyContainer.setEditorMode") }
    #[pyo3(signature = (name))]
    fn getEditorMode(&self, name: &str) -> Vec<PyObject> { todo!("PropertyContainer.getEditorMode") }
    #[pyo3(signature = (name))]
    fn getGroupOfProperty(&self, name: &str) -> String { todo!("PropertyContainer.getGroupOfProperty") }
    #[pyo3(signature = (name, group))]
    fn setGroupOfProperty(&self, name: &str, group: &str) -> () { todo!("PropertyContainer.setGroupOfProperty") }
    #[pyo3(signature = (name, val))]
    fn setPropertyStatus(&self, name: &str, val: PyObject) -> () { todo!("PropertyContainer.setPropertyStatus") }
    #[pyo3(signature = (name = ""))]
    fn getPropertyStatus(&self, name: &str) -> Vec<PyObject> { todo!("PropertyContainer.getPropertyStatus") }
    #[pyo3(signature = (name))]
    fn getDocumentationOfProperty(&self, name: &str) -> String { todo!("PropertyContainer.getDocumentationOfProperty") }
    #[pyo3(signature = (name, docstring))]
    fn setDocumentationOfProperty(&self, name: &str, docstring: &str) -> () { todo!("PropertyContainer.setDocumentationOfProperty") }
    #[pyo3(signature = (name))]
    fn getEnumerationsOfProperty(&self, name: &str) -> Vec<PyObject> { todo!("PropertyContainer.getEnumerationsOfProperty") }
    #[pyo3(signature = (Property, *, Compression = 3))]
    fn dumpPropertyContent(&self, Property: &str, Compression: i64) -> PyObject { todo!("PropertyContainer.dumpPropertyContent") }
    #[pyo3(signature = (name, obj))]
    fn restorePropertyContent(&self, name: &str, obj: PyObject) -> () { todo!("PropertyContainer.restorePropertyContent") }
    #[pyo3(signature = (oldName, newName))]
    fn renameProperty(&self, oldName: &str, newName: &str) -> () { todo!("PropertyContainer.renameProperty") }
}

#[pymodule]
fn ferrocad_gen(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<Document>()?;
    m.add_class::<DocumentObject>()?;
    m.add_class::<PropertyContainer>()?;
    Ok(())
}
